[package]
name = "email_project"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
tokio = { version = "1.45.1", features = ["full"] }
serde = { version = "1", features = ["derive"]}

[dev-dependencies]
reqwest = "0.12.19"